# dynmap-mobs configuration
#
update:
  # Seconds between position updates for mobs
  period: 5.0
  # Seconds between position updates for vehicles
  vehicleperiod: 10.0
  # Round position to given unit
  resolution: 1.0
  # Make markers hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky(disable hide))
  hideifshadow: 4
  # Make markers hidden when they are under cover (#=sky light level,0=underground,15=open to sky(disable hide))
  hideifundercover: 15
  # Mob updates per tick (prevent lag spikes when large number of mobs)
  mobs-per-tick: 20
  # Vehicle updates per tick (prevent lag spikes when large number of vehicles)
  vehicles-per-tick: 20

mocreat_mobs:
  bear: false
  bigcat: false
  bird: false
  boar: false
  bunny: false
  caveogre: false
  crocodile: false
  deer: false
  dolphin: false
  duck: false
  fireogre: false
  fishy: false
  flamewraith: false
  fox: false
  goat: false
  hellrat: false
  horse: false
  jellyfish: false
  kitty: false
  mouse: false
  ogre: false
  ostrich: false
  polarbear: false
  rat: false
  ray: false
  scorpion: false
  shark: false
  snake: false
  turtle: false
  werewolf: false
  wildwolf: false
  wraith: false

hostile_mobs:
  blaze: true
  cavespider: true
  creeper: true
  drowned: true
  elderguardian: true
  enderdragon: true
  enderman: true
  endermite: true
  evoker: true
  ghast: true
  giant: true
  guardian: true
  hoglin: true
  husk: true
  illusioner: true
  magmacube: true
  phantom: true
  piglin: true
  pillager: true
  ravager: true
  shulker: true
  silverfish: true
  skeleton: true
  slime: true
  spider: true
  spiderjockey: true
  stray: true
  vex: true
  vindicator: true
  witch: true
  wither: true
  witherskeleton: true
  zoglin: true
  zombie: true
  zombiepigman: true
  zombievillager: true

passive_mobs:
  bat: true
  cat: true
  chicken: true
  chickenjockey: true
  cod: true
  cow: true
  donkey: true
  golem: true
  llama: true
  mooshroom: true
  mule: true
  ocelot: true
  panda: true
  parrot: true
  pig: true
  pufferfish: true
  rabbit: true
  salmon: true
  sheep: true
  skeletonhorse: true
  snowgolem: true
  squid: true
  strider: true
  tamedwolf: true
  traderllama: true
  tropicalfish: true
  vanilladolphin: true
  vanillafox: true
  vanillahorse: true
  vanillapolarbear: true
  vanillaturtle: true
  villager: true
  wandering_trader: true
  wolf: true
  zombiehorse: true
  bee: true

vehicles:
  # Specific minecart types
  command-minecart: false
  explosive-minecart: false
  hopper-minecart: false
  powered-minecart: false
  spawner-minecart: false
  storage-minecart: false
  minecart: false
  # Boats
  boat: false
  
mocreatlayer:
  name: "Mo'Creatures Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false

hostilelayer:
  name: "Hostile Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false

passivelayer:
  name: "Passive Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  
vehiclelayer:
  name: "Vehicles"
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 11
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  